
#[allow(non_camel_case_types)]
#[derive(Debug)]
pub enum BusinessError {
	UNSPECIFIED_ERROR,
	UNALIGNED_TIMEFRAME,
	INCORRECT_ARGUMENT_ORDER,
	CANNOT_CREATE_SQL_TRANSACTION,
	SQL_TRANSACTION_ERROR,
}
